#使用 tf.data 加载 pandas dataframes

本教程提供了如何将 pandas dataframes 加载到 tf.data.Dataset。

本教程使用了一个小型数据集，由克利夫兰诊所心脏病基金会（Cleveland Clinic Foundation for Heart Disease）提供. 此数据集中有几百行CSV。每行表示一个患者，每列表示一个属性（describe）。我们将使用这些信息来预测患者是否患有心脏病，这是一个二分类问题。

##使用 pandas 读取数据

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  %tensorflow_version 2.x
except Exception:
  pass

import pandas as pd
import tensorflow as tf


TensorFlow 2.x selected.


下载包含心脏数据集的 csv 文件。

In [2]:
csv_file = tf.keras.utils.get_file('heart.csv','https://storage.googleapis.com/applied-dl/heart.csv')

16384/13273 [=====================================] - 0s 0us/step


使用 pandas 读取 csv 文件。

In [0]:
df = pd.read_csv(csv_file)

In [4]:
df.head()

age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0

[5 rows x 14 columns]

In [5]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

将 thal 列（数据帧（dataframe）中的 object ）转换为离散数值。

In [0]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

In [7]:
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   1       145   233    1  ...      0      2.3      3   0     2       0
1   67    1   4       160   286    0  ...      1      1.5      2   3     3       1
2   67    1   4       120   229    0  ...      1      2.6      2   2     4       0
3   37    1   3       130   250    0  ...      0      3.5      3   0     3       0
4   41    0   2       130   204    0  ...      0      1.4      1   0     3       0

[5 rows x 14 columns]

##使用 tf.data.Dataset 读取数据
使用 tf.data.Dataset.from_tensor_slices 从 pandas dataframe 中读取数值。

使用 tf.data.Dataset 的其中一个优势是可以允许您写一些简单而又高效的数据管道（data pipelines)。从 loading data guide 可以了解更多。

In [0]:
target = df.pop('target')

In [0]:
dataset = tf.data.Dataset.from_tensor_slices((df.values,target.values))

In [11]:
for feat,targ in dataset.take(5):
  print('Features:{}, Target:{}'.format(feat,targ))

Features:[ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target:0
Features:[ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target:1
Features:[ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target:0
Features:[ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target:0
Features:[ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target:0


由于 pd.Series 实现了 __array__ 协议，因此几乎可以在任何使用 np.array 或 tf.Tensor 的地方透明地使用它。

In [12]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int32, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
     

随机读取（shuffle）并批量处理数据集。

In [0]:
train_dataset = dataset.shuffle(len(df)).batch(1)

###创建并训练模型

In [0]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10,activation='relu'),
    tf.keras.layers.Dense(10,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
  ])

  model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [16]:
model = get_compiled_model()
model.fit(train_dataset,epochs=15)

Train for 303 steps
Epoch 1/15
303/303 [==============================] - 3s 9ms/step - loss: 2.7861 - accuracy: 0.6139
Epoch 2/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5698 - accuracy: 0.7393
Epoch 3/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5390 - accuracy: 0.7393
Epoch 4/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5614 - accuracy: 0.7195
Epoch 5/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5318 - accuracy: 0.7327
Epoch 6/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5376 - accuracy: 0.7459
Epoch 7/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5069 - accuracy: 0.7426
Epoch 8/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5089 - accuracy: 0.7426
Epoch 9/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5118 - accuracy: 0.7195
Epoch 10/15
303/303 [==============================] - 1s 3ms/step - loss: 0.500

##代替特征列
将字典作为输入传输给模型就像创建 tf.keras.layers.Input 层的匹配字典一样简单，应用任何预处理并使用 functional api。 您可以使用它作为 feature columns 的替代方法。

In [0]:
inputs = {key:tf.keras.layers.Input(shape=(),name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()),axis=-1)

x = tf.keras.layers.Dense(10,activation='relu')(x)
output = tf.keras.layers.Dense(1,activation='sigmoid')(x)

model_func = tf.keras.Model(inputs=inputs,outputs=output)

model_func.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics=['accuracy'])

与 tf.data 一起使用时，保存 pd.DataFrame 列结构的最简单方法是将 pd.DataFrame 转换为 dict ，并对该字典进行切片。

In [0]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'),target.values)).batch(16)

In [19]:
for dict_slice in dict_slices.take(1):
  print(dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [20]:
model_func.fit(dict_slices,epochs=15)

Train for 19 steps
Epoch 1/15
19/19 [==============================] - 0s 21ms/step - loss: 13.1156 - accuracy: 0.2574
Epoch 2/15
19/19 [==============================] - 0s 4ms/step - loss: 3.8790 - accuracy: 0.4158
Epoch 3/15
19/19 [==============================] - 0s 4ms/step - loss: 2.6262 - accuracy: 0.6568
Epoch 4/15
19/19 [==============================] - 0s 4ms/step - loss: 2.4427 - accuracy: 0.6139
Epoch 5/15
19/19 [==============================] - 0s 4ms/step - loss: 2.2839 - accuracy: 0.5908
Epoch 6/15
19/19 [==============================] - 0s 4ms/step - loss: 2.0003 - accuracy: 0.6073
Epoch 7/15
19/19 [==============================] - 0s 4ms/step - loss: 1.6248 - accuracy: 0.6271
Epoch 8/15
19/19 [==============================] - 0s 4ms/step - loss: 1.4620 - accuracy: 0.6766
Epoch 9/15
19/19 [==============================] - 0s 4ms/step - loss: 1.3706 - accuracy: 0.6733
Epoch 10/15
19/19 [==============================] - 0s 4ms/step - loss: 1.2985 - accuracy: 0.683